providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "gunicorn app:app"
